### DISCUSSION TITLE
Change conda repository channel

### DISCUSSION THREAD

**Discussion by ds-lukaslangr** [daipe-ai/daipe#2] [Announcements]
Due to [Anconda's Terms of service](https://www.anaconda.com/terms-of-service) we are not allowed to use their repository for commercial purposes. Therefore it is necessary to switch to `conda-forge`, a community driven repository.

Example of `environment.yml` for DBR 7.3:

```yaml
name: daipedemo
channels:
  - conda-forge
dependencies:
  - python=3.7.5
  - pip=20.0.2
  - setuptools=45.2.0
```

To make sure you're not using `defaults` run globally:
- `conda config --remove channels defaults`
- `conda config --append channels conda-forge`
