### DISCUSSION TITLE
Freeze pip and setuptools versions

### DISCUSSION THREAD

**Discussion by ds-lukaslangr** [daipe-ai/daipe#4] [Announcements]
Due to an error in a new version of setuptools it is necessary to **freeze** versions of `pip` and `setuptools` in `environment.yml`

Example for DBR 7.3 LTS:

```yaml
name: daipedemo
channels:
  - conda-forge
dependencies:
  - python=3.7.5
  - pip=20.0.2
  - setuptools=45.2.0
```

Correct `python`, `pip` and `setuptools` version for specific DBR versions can be found at:

[https://docs.databricks.com/release-notes/runtime/7.3.html](https://docs.databricks.com/release-notes/runtime/7.3.html)

[https://docs.databricks.com/release-notes/runtime/8.4.html](https://docs.databricks.com/release-notes/runtime/8.4.html)
[https://docs.databricks.com/release-notes/runtime/9.0.html](https://docs.databricks.com/release-notes/runtime/9.0.html)
